[workspace]
members = [
    "seam",
]
resolver = "2"

[workspace.package]
authors = ["Adam McKee <adam.be.g84d@gmail.com>"]
edition = "2021"
license = "BSD-2-Clause"
repository = "https://github.com/eighty4/seam"
